# Dockerfile for ailist

FROM python:3.8.1

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Install required Python packages
RUN git clone https://github.com/databio/AIList.git
RUN cd AIList && git checkout 63278b0 && make

ENV PATH="/AIList/bin/:${PATH}"
