# Dockerfile for R for pipelines.
# This based on a bioconductor container, with packages included to run
# lab pipelines. 

FROM bioconductor/bioconductor_docker:RELEASE_3_12

MAINTAINER Nathan Sheffield <nathan@code.databio.org>

# Install required Bioconductor packages
RUN Rscript -e 'install.packages("devtools")'
RUN Rscript -e 'install.packages("pepr")'
RUN Rscript -e 'install.packages("BiocManager")'
RUN Rscript -e 'BiocManager::install("GenomicRanges")'
RUN Rscript -e 'BiocManager::install("Biostrings")'
RUN Rscript -e 'BiocManager::install("GenomicDistributions")'
RUN Rscript -e 'BiocManager::install("GenomicDistributionsData")'

RUN git clone https://github.com/databio/peppro.git
RUN cd peppro && Rscript -e 'devtools::install(file.path("PEPPROr/"), dependencies=TRUE, repos="https://cloud.r-project.org/")'
RUN rm -rf peppro

RUN git clone https://github.com/databio/pepatac.git
RUN cd pepatac && Rscript -e 'devtools::install(file.path("PEPATACr/"), dependencies=TRUE, repos="https://cloud.r-project.org/")'
RUN rm -rf pepatac
